version: 2.1

jobs:
  deploy_to_kubernetes:
    docker:
      - image: alpine/k8s:1.26.13
    steps:
      - checkout

      - run:
          name: Set Up Kubernetes
          command: |
            echo $KUBECONFIG_DATA | base64 -d > kubeconfig
            export KUBECONFIG=kubeconfig
            kubectl config use-context arn:aws:eks:ap-southeast-2:339713019591:cluster/test-1

      - run:
          name: Debug Kubeconfig
          command: |
            kubectl config current-context



      # Apply MongoDB Secrets
      - run:
          name: Apply MongoDB Secrets
          command: kubectl apply -f mongo-secrets.yaml

      # Deploy MongoDB
      - run:
          name: Deploy MongoDB
          command: kubectl apply -f mongo.yaml

      # Apply MongoDB ConfigMap
      - run:
          name: Apply MongoDB ConfigMap
          command: kubectl apply -f mongo-configMap.yaml

      # Deploy Mongo Express
      - run:
          name: Deploy Mongo Express
          command: kubectl apply -f mongo-express.yaml

      # Create Docker Registry Secret for AWS ECR
      - run:
          name: Create Docker Registry Secret
          command: |
            echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) | kubectl create secret docker-registry ecr-secret --docker-server=339713019591.dkr.ecr.ap-southeast-2.amazonaws.com --docker-username=AWS --docker-password-stdin --docker-email=ranjan.s.1227@gmailcom

      # Deploy My App
      - run:
          name: Deploy My Application
          command: kubectl apply -f my-app.yaml

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_to_kubernetes
