version: 2.1

jobs:
  deploy_to_kubernetes:
    docker:
      - image: alpine/k8s:1.26.13
    steps:
      - checkout

      - run:
          name: Set Up Kubernetes
          command: |
            echo $KUBECONFIG_DATA | base64 -d > kubeconfig
            export KUBECONFIG=kubeconfig
            kubectl config use-context arn:aws:eks:ap-southeast-2:339713019591:cluster/test-1
            kubectl config current-context
            kubectl config view
            kubectl apply -f mongo-secrets.yaml
            kubectl apply -f mongo.yaml
            kubectl apply -f mongo-configMap.yaml
            kubectl apply -f mongo-express.yaml
            kubectl apply -f my-app.yaml

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_to_kubernetes


      # Was Used for creating the ecr secret.  
      #PASSWORD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      #echo "Creating Docker registry secret..."
      #kubectl create secret docker-registry ecr-secret --docker-server=339713019591.dkr.ecr.ap-southeast-2.amazonaws.com --docker-username=AWS --docker-password="${PASSWORD}" 
